version: '3'

services:
    rundeck:
        build:
            context: ./
            args:
                RUNDECK_IMAGE: ${RUNDECK_IMAGE:-rundeck/rundeck:3.4.4}
        tty: true
        environment:
            RUNDECK_GRAILS_URL: "${RUNDECK_GRAILS_URL}"
            RUNDECK_SERVER_FORWARDED: "${RUNDECK_SERVER_FORWARDED}"
        volumes:
          - "data:/home/rundeck/server/data"
    nginx:
        image: nginx
        links:
          - rundeck
        volumes:
          - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
          - 80:80
volumes:
    data:
    dbdata:
